# --- naive kernel ---
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 1000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 10000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 100000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 1000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 2000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 2500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 3000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 3800000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 5000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 6500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 9000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 10000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 15000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu 20000000

# --- shared-memory kernel ---
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 1000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 10000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 100000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 1000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 2000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 2500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 3000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 3800000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 5000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 6500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 9000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 10000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 15000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_shared 20000000

# --- coalesced/vectorized kernel ---
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 1000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 10000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 100000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 1000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 2000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 2500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 3000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 3800000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 5000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 6500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 9000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 10000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 15000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_coalesced 20000000


# --- compute kernel ---
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 1000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 10000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 100000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 1000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 2000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 2500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 3000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 3800000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 5000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 6500000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 9000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 10000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 15000000
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/oseghalef/code/PV_Final/pv_gpu_compute 20000000

